<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete question answer');

if(isset($_GET['question_answer_id']))
{
    $question_answer_id = urldecode($_GET['question_answer_id']);
    require_once 'form_data_question_answer.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_question_answer.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/question_answer.php';
        $dbh_question_answer = new question_answer;

        $object_name = 'dbh_question_answer';
        require 'components/create_form_data.php';


        $dbh_question_answer->delete($arr_form_data);

        redirect("listview_question_answer.php?$query_string");
    }
}
require 'subclasses/question_answer_html.php';
$html = new question_answer_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('question_answer_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();