<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit question answer');

$show_modal = FALSE;
if(isset($_GET['question_answer_id']))
{
    $question_answer_id = urldecode($_GET['question_answer_id']);
    require 'form_data_question_answer.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
	init_var($_POST['btn_cancel2']);
    init_var($_POST['btn_submit2']);
    require 'components/query_string_standard.php';
    require 'subclasses/question_answer.php';
    $dbh_question_answer = new question_answer;

    $object_name = 'dbh_question_answer';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_question_answer.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_question_answer->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_question_answer->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
			$show_modal = TRUE;
            

           
        }
    }
	  if($_POST['btn_submit2'])
	{
		
		//debug($arr_form_data);
		 $dbh_question_answer->edit($arr_form_data);
        redirect("listview_question_answer.php?$query_string");
	}
	
	if($_POST['btn_cancel2'])
	{
		$show_modal = FALSE;
	}
}
require 'subclasses/question_answer_html.php';
$html = new question_answer_html;
$modal_message = "Are you sure you want to continue?";
$html->draw_header('Edit %%', $message, $message_type);
if($show_modal)
{
	$html->draw_container_div_start_modal($modal_message);
}
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('question_answer_id');

$html->draw_controls('edit');

$html->draw_footer();