<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit advertiser');

if(isset($_GET['advertiser_id']))
{
    $advertiser_id = urldecode($_GET['advertiser_id']);
    require 'form_data_advertiser.php';

}
	$show_modals = FALSE;
if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
	init_var($_POST['btn_submit2']);
	init_var($_POST['btn_cancel2']);
    require 'components/query_string_standard.php';
    require 'subclasses/advertiser.php';
    $dbh_advertiser = new advertiser;

    $object_name = 'dbh_advertiser';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_advertiser.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_advertiser->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_advertiser->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {		
			$show_modal = TRUE;
        }	
    }
	if($_POST['btn_submit2'])
	{
		//$arr_form_data['question'] = $_POST['question'];
		//debug($arr_form_data);
		    $dbh_advertiser->edit($arr_form_data);

            redirect("listview_advertiser.php?$query_string");
	}
	
	if($_POST['btn_cancel2'])
	{
		$show_modal = FALSE;
	}
}
require 'subclasses/advertiser_html.php';
$html = new advertiser_html;
$modal_message ="Are you sure you want to continue?";
$html->draw_header('Edit %%', $message, $message_type);
	if($show_modals)
	{
		$html->draw_container_div_start_modal($modal_message);
	}

$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('advertiser_id');

$html->draw_controls('edit');

$html->draw_footer();