<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete company');

if(isset($_GET['company_id']))
{
    $company_id = urldecode($_GET['company_id']);
    require_once 'form_data_company.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_company.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/company.php';
        $dbh_company = new company;

        $object_name = 'dbh_company';
        require 'components/create_form_data.php';

        require_once 'subclasses/trivia.php';
        $dbh_trivia = new trivia;
        $dbh_trivia->delete_many($arr_form_data);

        require_once 'subclasses/company_ad.php';
        $dbh_company_ad = new company_ad;
        $dbh_company_ad->delete_many($arr_form_data);

        require_once 'subclasses/advertiser.php';
        $dbh_advertiser = new advertiser;
        $dbh_advertiser->delete_many($arr_form_data);


        $dbh_company->delete($arr_form_data);

        redirect("listview_company.php?$query_string");
    }
}
require 'subclasses/company_html.php';
$html = new company_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('company_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();