<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit billboard location');

if(isset($_GET['billboard_location_id']))
{
    $billboard_location_id = urldecode($_GET['billboard_location_id']);
    require 'form_data_billboard_location.php';

}
$show_modal = FALSE;
if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    init_var($_POST['btn_cancel2']);
    init_var($_POST['btn_submit2']);
    require 'components/query_string_standard.php';
    require 'subclasses/billboard_location.php';
    $dbh_billboard_location = new billboard_location;

    $object_name = 'dbh_billboard_location';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_billboard_location.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_billboard_location->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_billboard_location->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $show_modal = TRUE;
            //$dbh_billboard_location->edit($arr_form_data);

           // redirect("listview_billboard_location.php?$query_string");
        }
    }
    if($_POST['btn_submit2'])
	{
		$dbh_billboard_location->edit($arr_form_data);
		//debug($arr_form_data);
		  redirect("listview_billboard_location.php?$query_string");
		 
   
	}
	
	if($_POST['btn_cancel2'])
	{
		$show_modal = FALSE;
	}
}
require 'subclasses/billboard_location_html.php';
$html = new billboard_location_html;
$modal_message = "Are you sure you want to continue?";
$html->draw_header('Edit %%', $message, $message_type);
if($show_modal)
{
	$html->draw_container_div_start_modal($modal_message);
}
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('billboard_location_id');

//$html->draw_controls('edit');
<<<<<<< HEAD
$html->draw_container_div_start();
$html->draw_fieldset_header('Customized Form w/ GMaps');
=======

$html->draw_container_div_start();
$html->draw_fieldset_header('Billboard Location Assigner');
>>>>>>> 63f056e43ad55a53e279c4f2f5f4c57ff4ec161c
$html->draw_fieldset_body_start();
echo '<table class="input_form">';


$html->draw_field('address');
$html->draw_field('postal_code');
$html->draw_field('latitude');
$html->draw_field('longitude');
require 'thirdparty/googleMaps/samp.php';


echo '<tr><td colspan="2">';

echo '</td></tr>';


echo '</table>';
$html->autofocus('position_title');
$html->draw_fieldset_body_end();
$html->draw_fieldset_footer_start();
$html->draw_submit_cancel(FALSE);
<<<<<<< HEAD
=======


>>>>>>> 63f056e43ad55a53e279c4f2f5f4c57ff4ec161c

$html->draw_footer();