<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit player answered question');

if(isset($_GET['player_answered_question_id']))
{
    $player_answered_question_id = urldecode($_GET['player_answered_question_id']);
    require 'form_data_player_answered_question.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/player_answered_question.php';
    $dbh_player_answered_question = new player_answered_question;

    $object_name = 'dbh_player_answered_question';
    require 'components/create_form_data.php';

    extract($arr_form_data);
	
	
    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_player_answered_question.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_player_answered_question->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_player_answered_question->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_player_answered_question->edit($arr_form_data);

            redirect("listview_player_answered_question.php?$query_string");
        }
    }
}

require 'subclasses/player_answered_question_html.php';
$html = new player_answered_question_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('player_answered_question_id');

$html->draw_controls('edit');

$html->draw_footer();