<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete company ad');

if(isset($_GET['company_ad_id']))
{
    $company_ad_id = urldecode($_GET['company_ad_id']);
    require_once 'form_data_company_ad.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_company_ad.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/company_ad.php';
        $dbh_company_ad = new company_ad;

        $object_name = 'dbh_company_ad';
        require 'components/create_form_data.php';

        require_once 'subclasses/question.php';
        $dbh_question = new question;
        $dbh_question->delete_many($arr_form_data);


        $dbh_company_ad->delete($arr_form_data);

        redirect("listview_company_ad.php?$query_string");
    }
}
require 'subclasses/company_ad_html.php';
$html = new company_ad_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('company_ad_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();