<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete player');

if(isset($_GET['player_id']))
{
    $player_id = urldecode($_GET['player_id']);
    require_once 'form_data_player.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_player.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/player.php';
        $dbh_player = new player;

        $object_name = 'dbh_player';
        require 'components/create_form_data.php';

        require_once 'subclasses/player_answered_question.php';
        $dbh_player_answered_question = new player_answered_question;
        $dbh_player_answered_question->delete_many($arr_form_data);


        $dbh_player->delete($arr_form_data);

        redirect("listview_player.php?$query_string");
    }
}
require 'subclasses/player_html.php';
$html = new player_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('player_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();