<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit billboard location');

if(isset($_GET['billboard_location_id']))
{
    $billboard_location_id = urldecode($_GET['billboard_location_id']);
    require 'form_data_billboard_location.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/billboard_location.php';
    $dbh_billboard_location = new billboard_location;

    $object_name = 'dbh_billboard_location';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_billboard_location.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_billboard_location->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_billboard_location->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            require_once 'subclasses/company_ad.php';
            $dbh_company_ad = new company_ad;
            $dbh_company_ad->delete_many($arr_form_data);

            for($a=0; $a<$company_ad_count;$a++)
            {
                $cf_company_ad_ad_start_date[$a] = $cf_company_ad_ad_start_date_year[$a] . '-' . $cf_company_ad_ad_start_date_month[$a] . '-' . $cf_company_ad_ad_start_date_day[$a];
               $cf_company_ad_ad_end_date[$a] = $cf_company_ad_ad_end_date_year[$a] . '-' . $cf_company_ad_ad_end_date_month[$a] . '-' . $cf_company_ad_ad_end_date_day[$a];
               
                $param = array(
                               'company_id'=>$cf_company_ad_company_id[$a],
                               'billboard_loc'=>$billboard_location_id,
                               'ad_start_date'=>$cf_company_ad_ad_start_date[$a],
                               'ad_end_date'=>$cf_company_ad_ad_end_date[$a],
                               'advertisement_name'=>$cf_company_ad_advertisement_name[$a]
                              );
                $dbh_company_ad->add($param);
            }


            $dbh_billboard_location->edit($arr_form_data);

            redirect("listview_billboard_location.php?$query_string");
        }
    }
}
require 'subclasses/billboard_location_html.php';
$html = new billboard_location_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('billboard_location_id');

$html->draw_controls('edit');

$html->draw_footer();